# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-18 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20170618_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kirrurl',
            options={'ordering': ['-id']},
        ),
    ]
